version: '3.8'

networks:
  pg-network:

services:
  usermng_postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: user_management
      POSTGRES_USER: GrabbingTheCode
      POSTGRES_PASSWORD: fun123
    ports:
      - "5432:5432"
    volumes:
      - db1_data:/var/lib/postgresql/data
    networks:
      - pg-network

  bookmng_postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: book_management
      POSTGRES_USER: GrabbingTheCode
      POSTGRES_PASSWORD: fun123
    ports:
      - "5433:5432"
    volumes:
      - db2_data:/var/lib/postgresql/data
    networks:
      - pg-network


volumes:
  db1_data:
  db2_data: