services:
  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: fun123
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: library_management
    ports:
      - "3308:3306"
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
