server:
  port: 8080

spring:
  application:
    name: Library-Management
  datasource:
    username: GrabbingTheCode
    password: fun123
    url: jdbc:postgresql://localhost:5433/book_management
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true